language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - "touch README"
  - "pip install . --use-mirrors --allow-external argparse"
  - "pip install -r test-requirements.txt --use-mirrors"
script: nosetests tests
