#!/usr/bin/env python

import sys
import platform

implementation = platform.python_implementation()
major, minor = sys.version_info[:2]
sys.stderr.write("This is {} {}.{} calling\n".format(implementation, major, minor))
