#!/usr/bin/env python

import sys
import platform

implementation = platform.python_implementation()
major, minor = sys.version_info[:2]
print "This is {0} {1}.{2} calling".format(implementation, major, minor)
